avaliacao_preferencia/livapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static



from .views import *

from . import views

app_name = 'livapp'
urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('<slug:slug>', views.post_detail, name='post_detail'),
    #path('criar/', views.post_create, name='post_create'),
    #path('sobre-nos/', views.about, name='about'),
    #path('contato/', views.contact, name='contact'),
    path('logar_usuario/', views.logar_usuario, name='logar_usuario'),
    path('cadastrar_usuario/', views.cadastrar_usuario, name='cadastrar_usuario'),
    #path('index', views.index, name="index"),
    path('', views.IndexView.as_view(), name='index'),
    #path('avatar/', views.post_create, name='avatar'),
    path('avatar/', views.avatar, name='avatar'),
    path('picture/', views.picture, name='picture'),
    path('pictureex/', views.pictureex, name='pictureex'),
    path('picturereforco/', views.picturereforco, name='picturereforco'),
    path('picturedica/', views.picturedica, name='picturedica'),
    path('pictureex2/', views.pictureex2, name='pictureex2'),
    path('picturereforco2/', views.picturereforco2, name='picturereforco2'),
    path('picturedica2/', views.picturedica2, name='picturedica2'),
    path('pictureex3/', views.pictureex3, name='pictureex3'),
    path('picturereforco3/', views.picturereforco3, name='picturereforco3'),
    path('picturedica3/', views.picturedica3, name='picturedica3'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('pictureexant3/', views.pictureexant3, name='pictureexant3'),
    path('final/', views.final, name='final'),
    
    re_path(r'^$', views.home, name="home"),
    re_path(r'^upload/', views.upload, name="upload"),
    
    path(r'pictureex/upload/', views.upload, name="upload"),
        
    re_path(r'^$', views.home2, name="home2"),
    path(r'picturereforco/upload/', views.upload, name="upload"),
    
    re_path(r'^$', views.home3, name="home3"),
    path(r'picturedica/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home4, name="home4"),
    path(r'pictureex2/upload/', views.upload, name="upload"), 
    
    path('pictureexrep1/', views.pictureexrep1, name='pictureexrep1'),
    path('pictureexrep2/', views.pictureexrep2, name='pictureexrep2'),
    #path('pictureexrep3/', views.pictureexrep3, name='pictureexrep3'),
    
    re_path(r'^$', views.home5, name="home5"),
    path(r'pictureexrep1/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home6, name="home7"),
    path(r'picturereforco2/upload/', views.upload, name="upload"),
    
    re_path(r'^$', views.home7, name="home7"),
    path(r'picturedica2/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home8, name="home8"),
    path(r'pictureexrep2/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home9, name="home9"),
    path(r'pictureex3/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home10, name="home10"),
    re_path(r'picturereforco3/upload/', views.upload, name="upload"),
    
    re_path(r'^$', views.home11, name="home11"),
    path(r'picturedica3/upload/', views.upload, name="upload"), 
    
    #re_path(r'^$', views.home12, name="home12"),
    #path(r'pictureexrep3/upload/', views.upload, name="upload"), 
    
    re_path(r'^$', views.home13, name="home13"),
    path(r'pictureexant3/upload/', views.upload, name="upload"), 
    
    re_path(r'^salvaavatar/', views.salvaavatar, name="salvaavatar"),
    path(r'avatar/salvaavatar/', views.salvaavatar, name="salvaavatar"),
    
    re_path(r'^salvaavatarbd/', views.salvaavatarbd, name="salvaavatarbd"),
    path(r'picturereforco3/salvaavatarbd/', views.salvaavatarbd, name="salvaavatarbd"),

    re_path(r'^recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'picture/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'pictureex/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'pictureexrep1/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'pictureex2/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'pictureexrep2/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    path(r'pictureex3/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),
    #path(r'pictureexrep3/recuperaavatar/', views.recuperaavatar, name="recuperaavatar"),

    
    
    


]

avaliacao_preferencia/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from livapp import views

urlpatterns = [
    path('livapp/', include('livapp.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

avaliacao_preferencia/livapp/models.py
import datetime
from django.db import models
from django.utils import timezone
import cv2
from ecapture import ecapture as ec
from django.contrib.auth.models import User





class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        
class Dados(models.Model):
    #id = CompositeKey(columns=['id', 'ciclo'])
    #id = models.ForeignKey(auth_user, models.DO_NOTHING,db_column='id')    
    #aluno = models.CharField(max_length=200, default='Aluno')
    #aluno = models.ManyToOneField(User, on_delete=models.CASCADE)
    TEMAS_CHOICES = (
        ('Bola', 'Bola'),
        ('Carro', 'Carro'),
        ('Doce', 'Doce'),
        ('Livro', 'Livro'),
    )
    AVATAR_CHOICES = (
        ('Menina2', 'Menina2'),
        ('Cachorro', 'Cachorro'),
        ('Menina', 'Menina'),
        ('Menino', 'Menino'),
        ('Coelho', 'Coelho'),
        ('Emoji', 'Emoji'),
        #('Super Heroi', 'Super Heroi'),
        #('Cachorro', 'Cachorro'),
        #('McQueen', 'McQueen'),
        #('Trem', 'Trem'),
    )
    aluno = models.ForeignKey(User, on_delete=models.CASCADE)
    ciclo = models.AutoField(primary_key=True)
    avatar = models.CharField(max_length=200, choices=AVATAR_CHOICES)
    tema_1 = models.CharField(max_length=200, choices=TEMAS_CHOICES)
    tema_2 = models.CharField(max_length=200, choices=TEMAS_CHOICES)
    tema_3 = models.CharField(max_length=200, choices=TEMAS_CHOICES)
    tema_4 = models.CharField(max_length=200, choices=TEMAS_CHOICES)
    def __str__(self):
        return str(self.aluno)
    
    class Meta:
        managed = True
        db_table = 'dados'
        unique_together = (('aluno', 'ciclo'),)



    

avaliacao_preferencia/usuarios/models.py
from django.db import models

# Create your models here.

avaliacao_preferencia/livapp/forms.py
from django.forms import ModelForm
from .models import Dados #<br>
class PostForm(ModelForm):
    class Meta:
        model = Dados
        fields = ['ciclo', 'avatar', 'tema_1', 'tema_2', 'tema_3', 'tema_4']
        
        
        
        

avaliacao_preferencia/usuarios/views.py
from django.shortcuts import render

# Create your views here.

avaliacao_preferencia/livapp/templates/livapp/dica2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


		<title>Ops!</title>
		
		{% load static %}
<link rel="shortcut icon" href="{% static 'livapp/images/favicon.png' %}"/>	
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- Tema -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'livapp/style.css' %}">
	

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>

		
		function recebevalor(){
            //var text = document.getElementById('text-to-analyze').value;
			//alert("Funcao enviarvalor"); 
            document.getElementById("myImage").src="/static/livapp/images/"+ localStorage.getItem('avatar')+"_triste.gif";
			
       }
		
		
		function uploadFoto(){
		
			
                var data = {};
				data["file"] = document.getElementById("arquivo").value;
				data["tema"] = localStorage.getItem('tema');
				
				
				
				/*if(data["file"] == "data:,")
				{
					let abc = document.getElementById("screenshot-button");
					abc.click();
					abc = document.getElementById("botao_submit");
					abc.click();
					return;
				}*/
				
				data["pagina"] = document.getElementById("pagina").value;
		
			$.ajax({
                  type: "POST",
                  url: "{{ request.build_absolute_uri }}upload/",
				  
                  
                    enctype: 'multipart/form-data',
					data: data,
					
                    cache: false, // desabilitar o "cache"
                    
                  success: function(data){
                      console.log("success");
                      console.log(data);
					  
					  window.location.href="{% url 'livapp:pictureex2' %}"
					  return false;
					  
                  },
                  failure: function(data){
                      console.log("failure");
                      console.log(data);
					  return false;
                  },
              });
			
			return false; // avoid to execute the actual submit of the form.
		}
		
		
		// this is the id of the submit button
		
		/*
$("#botao_submit").click(function() {

    var url = "path/to/your/script.php"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: "{{ request.build_absolute_uri }}upload/",
           data: $("#fileUploadForm").serialize(), // serializes the form's elements.
           success: function(data)
           {
               alert(data); // show response from the php script.
           }
         });

    return false; // avoid to execute the actual submit of the form.
});*/
		
		
		function startPage(){	
		recebevalor();	
		tirarFoto();
	
	
}

function tirarFoto(){

setTimeout(function(){
      
      let botao = document.getElementById("screenshot-button");
		botao.click();
       botao = document.getElementById("botao_submit");
  botao.click();
    }, 5000);
}




//window.onload = startPage;
		

		
    </script>			
</head>




<body class="temas" onload="startPage()">

<audio autoplay="autoplay"  preload="auto">
	<source src="{% static 'livapp/audios/dica.wav' %}" type="audio/mpeg"/>
</audio>

<div id="screenshot" style="text-align:center;" hidden>
  <canvas id="canvas"></canvas>

  <video class="videostream" autoplay="" ></video>
  <img id="screenshot-img" >
   <p><button class="capture-button" >Capture video</button></p>
</div>

<div class="container">
<h1 class="page-header">
					<!--Vamos tentar de novo!-->
					</h1>
					<div class="row">

<div>


<div class="col-sm-12 col-md-3">
		<!--<img border="0" width="420" height="205" id="reforco" src="{% static 'livapp/images/sad.gif' %}">-->
			
		
		<button id="screenshot-button" hidden >OK</button>
		</div>
			
		<div class="col-sm-12 col-md-6">
		 <img border="0" id="myImage" width="170" height="155">
		 	
		
		</div>
		
		
		
		</div>
		
	
	
	</div>
	</div>
<script>

const constraints = {
  video: true,
};

const captureVideoButton = document.querySelector(
  "#screenshot .capture-button"
);
const screenshotButton = document.querySelector("#screenshot-button");


const img = document.querySelector("#screenshot img");


const video = document.querySelector("#screenshot video");


navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
  video.srcObject = stream;
});

const canvas = document.getElementById("canvas");

captureVideoButton.onclick = function () {
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then(handleSuccess)
    .catch(handleError);
};

screenshotButton.onclick = video.onclick = function () {
//window.location.replace("{% url 'livapp:picture' %}");
  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  canvas.getContext("2d").drawImage(video, 0, 0);

  // Other browsers will fall back to image/png
  img.src = canvas.toDataURL("image/webp");  
  
  
  
  document.getElementById("arquivo").value=canvas.toDataURL("image/jpeg",0.9);
  
  /*setTimeout(function(){
      let abc = document.getElementById("botao_submit");
  abc.click();
    }, 3000);*/
};


function handleSuccess(stream) {
  screenshotButton.disabled = false;
  video.srcObject = stream;
}

function handleError(error) {
  console.error("Error: ", error);
}




</script>

<h1>
      {{what}}
  </h1>
  <table>
    <tr>
      <td>
	  
	 
	  
        
          
		  <input type="hidden" name="file" id="arquivo"/>
          <br />
          <input type="hidden" name="pagina" id="pagina" value="dica"/>
		  
		  <button id="botao_submit"  onclick= "return uploadFoto()" hidden>submit</button>
        
      </td>
    </tr>
  </table>
    <font size="-2"><div class="navbar navbar-fixed-bottom" style="position:fixed;bottom:0;height:auto;margin-top:50px;width:100%;text-align:center" size="-4" >Imagens gratuitas retiradas de www.imagensanimadas.com, www.pngwing.com, www.gratispng.com e www.gyphy.com</div>
</font>
</body>
</html>

avaliacao_preferencia/livapp/templates/livapp/exe1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	

	    <title>Exercício 1</title>
	
		{% load static %}
<link rel="shortcut icon" href="{% static 'livapp/images/favicon.png' %}"/>
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- Tema -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'livapp/style.css' %}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>

        function recebevalor(){
            //var text = document.getElementById('text-to-analyze').value;
			//alert("Funcao enviarvalor"); 
            //document.getElementById("myImage").src="/static/livapp/images/"+ localStorage.getItem('avatar');
			
			
            document.getElementById("imagem1").src="/static/livapp/images/"+ localStorage.getItem('tema')+"_1.png";
			document.getElementById("imagem2").src="/static/livapp/images/"+ localStorage.getItem('tema')+"_2.png";
			
        }
		
		function uploadFoto2(){
			alert('abc');
		}
		
		
		
		
		function uploadFoto(){
		
			 var form = $('#fileUploadForm')[0];
                // crie um FormData {Object}
                var data = {};
				data["file"] = document.getElementById("arquivo").value;
				data["tema"] = localStorage.getItem('tema');
				
				
				
				/*if(data["file"] == "data:,")
				{
					let abc = document.getElementById("screenshot-button");
					abc.click();
					abc = document.getElementById("botao_submit");
					abc.click();
					return;
				}*/
				
				data["pagina"] =document.getElementById("pagina").value;
		
			$.ajax({
                  type: "POST",
                  url: "{{ request.build_absolute_uri }}upload/",
				  
                  
                    enctype: 'multipart/form-data',
					data: data,
					
                    cache: false, // desabilitar o "cache"
                    
                  success: function(data){
                      console.log("success");
                      console.log(data);
					  return false;
					  
                  },
                  failure: function(data){
                      console.log("failure");
                      console.log(data);
					  return false;
                  },
              });
			
			return false; // avoid to execute the actual submit of the form.
		}
		
		
		// this is the id of the submit button
		
		/*
$("#botao_submit").click(function() {

    var url = "path/to/your/script.php"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: "{{ request.build_absolute_uri }}upload/",
           data: $("#fileUploadForm").serialize(), // serializes the form's elements.
           success: function(data)
           {
               alert(data); // show response from the php script.
           }
         });

    return false; // avoid to execute the actual submit of the form.
});*/
		
		
		function startPage(){
	recebevalor();
	tirarFoto();
	
	
}

function tirarFoto(){

setTimeout(function(){
      
      let botao = document.getElementById("screenshot-button");
		botao.click();
       botao = document.getElementById("botao_submit");
  botao.click();
    }, 2000);
}




//window.onload = startPage;
		


		
    </script>			
	
</head>




<body class="temas" onload="startPage()">

<audio autoplay="autoplay"  preload="auto"  loop=true>
	<source src="{% static 'livapp/audios/exe1.wav' %}" type="audio/mpeg"/>
</audio>


<div id="screenshot" style="text-align:center;" hidden>
  <canvas id="canvas"></canvas>

  <video class="videostream" autoplay="" ></video>
  <img id="screenshot-img" >
   <p><button class="capture-button" >Capture video</button></p>
</div>


<div class="container">

		<br><br><br>
		

		<div class="row">
		
		<!--<div class="col-sm-12 col-md-6">
		 <img border="0" id="myImage" width="170" height="155">
		</div>-->
		
		<div class="col-xs-4 col-sm-4 col-md-4">
		<a href="{% url 'livapp:picturedica' %}"><img border="0"  id="imagem1"  class="img-responsive" style="max-width:100%;height: auto;max-height: 100%;text-align:center;margin:auto;display:block"></a>
		</div>
		
		
		<div class="col-xs-4 col-sm-4 col-md-4">
		<img border="0" class="img-responsive" style="max-width:100%;height: auto;max-height: 100%;text-align:center;margin:auto;display:block" src="{% static 'livapp/images/menino.png' %}">  <button id="screenshot-button" hidden >OK</button>
		</div>	
		
		<div class="col-xs-4 col-sm-4 col-md-4">
		<a href="{% url 'livapp:picturereforco' %}"><img border="0" id="imagem2" class="img-responsive" style="max-width:100%;height: auto;max-height: 100%;text-align:center;margin:auto;display:block"></a>
		</div>
		
		</div>
		
				
	</div>


<script>

const constraints = {
  video: true,
};

const captureVideoButton = document.querySelector(
  "#screenshot .capture-button"
);
const screenshotButton = document.querySelector("#screenshot-button");


const img = document.querySelector("#screenshot img");


const video = document.querySelector("#screenshot video");


navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
  video.srcObject = stream;
});

const canvas = document.getElementById("canvas");

captureVideoButton.onclick = function () {
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then(handleSuccess)
    .catch(handleError);
};

screenshotButton.onclick = video.onclick = function () {
//window.location.replace("{% url 'livapp:picture' %}");
  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  canvas.getContext("2d").drawImage(video, 0, 0);

  // Other browsers will fall back to image/png
  img.src = canvas.toDataURL("image/webp");  
  
  
  
  document.getElementById("arquivo").value=canvas.toDataURL("image/jpeg",0.9);
  
  /*setTimeout(function(){
      let abc = document.getElementById("botao_submit");
  abc.click();
    }, 3000);*/
};


function handleSuccess(stream) {
  screenshotButton.disabled = false;
  video.srcObject = stream;
}

function handleError(error) {
  console.error("Error: ", error);
}








</script>

<h1>
      {{what}}
  </h1>
  <table>
    <tr>
      <td>
	  
	 
	  
        
          
		  <input type="hidden" name="file" id="arquivo"/>
          <br />
          <input type="hidden" name="pagina" id="pagina" value="exe1"/>
		  
		  <button id="botao_submit"  onclick= "return uploadFoto()" hidden>submit</button>
        
      </td>
    </tr>
  </table>
  
  
  <font size="-2"><div class="navbar navbar-fixed-bottom" style="position:fixed;bottom:0;height:auto;margin-top:50px;width:100%;text-align:center" size="-4" >Imagens gratuitas retiradas de www.imagensanimadas.com, www.pngwing.com, www.gratispng.com e www.gyphy.com</div>
</font>
</body>
</html>

avaliacao_preferencia/livapp/templates/livapp/exe3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	

	    <title>Exercício 3</title>
	
		{% load static %}
<link rel="shortcut icon" href="{% static 'livapp/images/favicon.png' %}"/>
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- Tema -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'livapp/style.css' %}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>

        function recebevalor(){
            //var text = document.getElementById('text-to-analyze').value;
			//alert("Funcao enviarvalor"); 
            //document.getElementById("myImage").src="/static/livapp/images/"+ localStorage.getItem('avatar');
			
			document.getElementById("imagem1").src="/static/livapp/images/"+ localStorage.getItem('tema')+"_1.png";
			document.getElementById("imagem2").src="/static/livapp/images/"+ localStorage.getItem('tema')+"_2.png";
        }
		
		function uploadFoto2(){
			alert('abc');
		}
		
		
		
		
		function uploadFoto(){
		
			 var form = $('#fileUploadForm')[0];
                // crie um FormData {Object}
                var data = {};
				data["file"] = document.getElementById("arquivo").value;
				data["tema"] = localStorage.getItem('tema');
				
				
				
				/*if(data["file"] == "data:,")
				{
					let abc = document.getElementById("screenshot-button");
					abc.click();
					abc = document.getElementById("botao_submit");
					abc.click();
					return;
				}*/
				
				data["pagina"] =document.getElementById("pagina").value;
		
			$.ajax({
                  type: "POST",
                  url: "{{ request.build_absolute_uri }}upload/",
				  
                  
                    enctype: 'multipart/form-data',
					data: data,
					
                    cache: false, // desabilitar o "cache"
                    
                  success: function(data){
                      console.log("success");
                      console.log(data);
					  return false;
					  
                  },
                  failure: function(data){
                      console.log("failure");
                      console.log(data);
					  return false;
                  },
              });
			
			return false; // avoid to execute the actual submit of the form.
		}
		
		
		// this is the id of the submit button
		
		/*
$("#botao_submit").click(function() {

    var url = "path/to/your/script.php"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: "{{ request.build_absolute_uri }}upload/",
           data: $("#fileUploadForm").serialize(), // serializes the form's elements.
           success: function(data)
           {
               alert(data); // show response from the php script.
           }
         });

    return false; // avoid to execute the actual submit of the form.
});*/
		
		
		function startPage(){
	recebevalor();
	tirarFoto();
	
	
}

function tirarFoto(){

setTimeout(function(){
      
      let botao = document.getElementById("screenshot-button");
		botao.click();
       botao = document.getElementById("botao_submit");
  botao.click();
    }, 2000);
}




//window.onload = startPage;
		

		
    </script>			
	
</head>



<body class="temas" onload="startPage()">

<audio autoplay="autoplay"  preload="auto" loop=true>
	<source src="{% static 'livapp/audios/exe3.wav' %}" type="audio/mpeg"/>
</audio>

<div id="screenshot" style="text-align:center;" hidden>
  <canvas id="canvas"></canvas>

  <video class="videostream" autoplay="" ></video>
  <img id="screenshot-img" >
   <p><button class="capture-button" >Capture video</button></p>
</div>

<div class="container">

		<br><br><br>
		

		<div class="row">	
		
		<!--<div class="col-sm-12 col-md-6">
		 <img border="0" id="myImage" width="170" height="155">
		</div>-->
		
		<div class="col-xs-6 col-sm-6 col-md-6">
		<a href="{% url 'livapp:picturedica3' %}"><img border="0" id="imagem1"   width="140" height="140"></a>
		<button id="screenshot-button" hidden >OK</button>

		</div>
		
		<div class="col-xs-6 col-sm-6 col-md-6">
	
		<button id="screenshot-button" hidden >OK</button>
		<a href="{% url 'livapp:picturereforco3' %}"><img border="0" id="imagem2" width="140" height="140"></a>
		</div>
		
	</div>
	</div>
	
	</div>

<script>

const constraints = {
  video: true,
};

const captureVideoButton = document.querySelector(
  "#screenshot .capture-button"
);
const screenshotButton = document.querySelector("#screenshot-button");


const img = document.querySelector("#screenshot img");


const video = document.querySelector("#screenshot video");


navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
  video.srcObject = stream;
});

const canvas = document.getElementById("canvas");

captureVideoButton.onclick = function () {
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then(handleSuccess)
    .catch(handleError);
};

screenshotButton.onclick = video.onclick = function () {
//window.location.replace("{% url 'livapp:picture' %}");
  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  canvas.getContext("2d").drawImage(video, 0, 0);

  // Other browsers will fall back to image/png
  img.src = canvas.toDataURL("image/webp");  
  
  
  
  document.getElementById("arquivo").value=canvas.toDataURL("image/jpeg",0.9);
  
  /*setTimeout(function(){
      let abc = document.getElementById("botao_submit");
  abc.click();
    }, 3000);*/
};


function handleSuccess(stream) {
  screenshotButton.disabled = false;
  video.srcObject = stream;
}

function handleError(error) {
  console.error("Error: ", error);
}








</script>

<h1>
      {{what}}
  </h1>
  <table>
    <tr>
      <td>
	  
	 
	  
        
          
		  <input type="hidden" name="file" id="arquivo"/>
          <br />
          <input type="hidden" name="pagina" id="pagina" value="exe3"/>
		  
		  <button id="botao_submit"  onclick= "return uploadFoto()" hidden>submit</button>
        
      </td>
    </tr>
  </table>
</body>

<font size="-2"><div class="navbar navbar-fixed-bottom" style="position:fixed;bottom:0;height:auto;margin-top:50px;width:100%;text-align:center" size="-4" >Imagens gratuitas retiradas de www.imagensanimadas.com, www.pngwing.com, www.gratispng.com e www.gyphy.com</div>
</font>
</html>